# ==========================
# SoloLeveling System
# Exercise Database
# ==========================

EXERCISES = {

    "push_up": {
        "name": "ضغط",
        "image": "assets/exercises/push_up.jpg",
        "description": "تمرين أساسي لتقوية الجزء العلوي من الجسم.",
        "muscles": ["الصدر", "الأكتاف", "الترايسبس"],
        "difficulty": "سهل",
        "recommended_reps": "10 - 20",
        "recommended_time": None,
        "category": "قوة",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "squat": {
        "name": "سكوات",
        "image": "assets/exercises/squat.jpg",
        "description": "تمرين لتقوية عضلات الأرجل والمؤخرة.",
        "muscles": ["الفخذ الأمامي", "الفخذ الخلفي", "المؤخرة"],
        "difficulty": "سهل",
        "recommended_reps": "15 - 30",
        "recommended_time": None,
        "category": "قوة",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "plank": {
        "name": "بلانك",
        "image": "assets/exercises/plank.jpg",
        "description": "تمرين ثابت يقوي عضلات البطن والجذع.",
        "muscles": ["البطن", "أسفل الظهر", "الكتفين"],
        "difficulty": "متوسط",
        "recommended_reps": None,
        "recommended_time": "30 - 60 ثانية",
        "category": "ثبات",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "running": {
        "name": "الجري",
        "image": "assets/exercises/running.jpg",
        "description": "يحسن اللياقة وصحة القلب والرئتين.",
        "muscles": ["الساقان", "القلب", "الرئتان"],
        "difficulty": "متوسط",
        "recommended_reps": None,
        "recommended_time": "10 - 30 دقيقة",
        "category": "كارديو",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "wide_push_up": {
        "name": "ضغط واسع",
        "image": "assets/exercises/wide_push_up.jpg",
        "description": "نسخة من تمرين الضغط تركز أكثر على عضلات الصدر.",
        "muscles": ["الصدر", "الأكتاف", "الترايسبس"],
        "difficulty": "متوسط",
        "recommended_reps": "10 - 20",
        "recommended_time": None,
        "category": "قوة",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "diamond_push_up": {
        "name": "ضغط ماسي",
        "image": "assets/exercises/diamond_push_up.jpg",
        "description": "تمرين ضغط يركز على عضلات الترايسبس.",
        "muscles": ["الترايسبس", "الصدر", "الأكتاف"],
        "difficulty": "صعب",
        "recommended_reps": "8 - 15",
        "recommended_time": None,
        "category": "قوة",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "lunges": {
        "name": "لونجز",
        "image": "assets/exercises/lunges.jpg",
        "description": "تمرين لتقوية عضلات الأرجل وتحسين التوازن.",
        "muscles": ["الفخذ", "المؤخرة", "الساق"],
        "difficulty": "متوسط",
        "recommended_reps": "10 - 20",
        "recommended_time": None,
        "category": "قوة",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "jump_squat": {
        "name": "سكوات قفز",
        "image": "assets/exercises/jump_squat.jpg",
        "description": "تمرين انفجاري يجمع بين القوة والكارديو.",
        "muscles": ["الفخذ", "المؤخرة", "الساق"],
        "difficulty": "صعب",
        "recommended_reps": "10 - 20",
        "recommended_time": None,
        "category": "كارديو",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "side_plank": {
        "name": "بلانك جانبي",
        "image": "assets/exercises/side_plank.jpg",
        "description": "تمرين ثبات يركز على عضلات الجذع الجانبية.",
        "muscles": ["البطن الجانبي", "الجذع", "الأكتاف"],
        "difficulty": "متوسط",
        "recommended_reps": None,
        "recommended_time": "30 - 60 ثانية",
        "category": "ثبات",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "burpee": {
        "name": "بيربي",
        "image": "assets/exercises/burpee.jpg",
        "description": "تمرين شامل يرفع اللياقة ويحرق الطاقة.",
        "muscles": ["الجسم كامل"],
        "difficulty": "صعب",
        "recommended_reps": "10 - 20",
        "recommended_time": None,
        "category": "كارديو",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "jump_rope": {
        "name": "نط الحبل",
        "image": "assets/exercises/jump_rope.jpg",
        "description": "تمرين كارديو لتحسين التحمل والرشاقة.",
        "muscles": ["الساقان", "الكتف", "القلب"],
        "difficulty": "متوسط",
        "recommended_reps": None,
        "recommended_time": "5 - 15 دقيقة",
        "category": "كارديو",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "walking": {
        "name": "المشي",
        "image": "assets/exercises/walking.jpg",
        "description": "نشاط بسيط لتحسين الحركة والصحة العامة.",
        "muscles": ["الساقان"],
        "difficulty": "سهل",
        "recommended_reps": None,
        "recommended_time": "15 - 60 دقيقة",
        "category": "كارديو",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    },

    "stretching": {
        "name": "الإطالات",
        "image": "assets/exercises/stretching.jpg",
        "description": "تمارين لتحسين المرونة وتقليل التصلب.",
        "muscles": ["الجسم كامل"],
        "difficulty": "سهل",
        "recommended_reps": None,
        "recommended_time": "5 - 15 دقيقة",
        "category": "مرونة",
        "video_url": None,
        "execution_steps": [],
        "common_mistakes": [],
    }

}
